### ISSUE TITLE
Hidden button in templates

### ISSUE THREAD

**Issue by Mrowqa** [Bouke/django-two-factor-auth#256]
In templates there is:
```html
    {# hidden submit button to enable [enter] key #}
    <div style="margin-left: -9999px"><input type="submit" value=""/></div>
```
Why this instead of `class="hidden"` since templates assumes Bootstrap 3? Current code adds spacing between forms and wizard navigation buttons.

**Comment by Bouke** [comment]
This library doesn't assume Bootstrap 3, but uses it in the [default base template](https://github.com/Bouke/django-two-factor-auth/blob/master/two_factor/templates/two_factor/_base.html) that ships with the template. You can override this base template with a template that fits your site's layout. Requiring Bootstrap to hide a button is not desirable. Also the button should be rendered off-screen, not hidden, otherwise the `[enter]` key triggers the wrong action, as explained in the comment.
