### ISSUE TITLE
Pass Authentication Form to Two Factor login url

### ISSUE THREAD

**Issue by bobozar** [Bouke/django-two-factor-auth#273]
Awesome package. Got it working within miniutes. Now, my default authentication takes username or mobile phone as input in order for user to sign in. For my authentication, I passed my form to django auth login url. 

Two factor accepts username only. Now, how do I pass in my form for Two factor in order for users to login with either username or mobile phone?

**Comment by moggers87** [comment]
I assume you're using a custom user model - if you're set this up correctly then Django's `AuthenticationForm` should already have those fields for you.

Otherwise, you can override [LoginView.form_list](https://github.com/Bouke/django-two-factor-auth/blob/master/two_factor/views/core.py#L63) either by subclassing the view or passing in `form_list` to `as_view` (basically what you'd do with any other class based view)

**Comment by bobozar** [comment]
okay thanks! Now working. :)
