### ISSUE TITLE
Remember OTP token for hours

### ISSUE THREAD

**Issue by awais786** [Bouke/django-two-factor-auth#56]
I want to implement remember otp for few hours 10 hrs. Means on first attempt admin gives userid/password an then give the OTP and for next 10 hrs when admin try to login again then it asks for userid/password only and skip the OTP till the 10 hrs. 

Whats the best place to implement this in codebase.

**Comment by shanx** [comment]
I would love to have a look at your work! Since I'm looking into implementing this myself, I don't see it in your fork.

**Comment by danielquinn** [comment]
I ended up here as I was trying to figure out how to do this and haven't had any success yet.  Was this issue solved in some other way or abandoned as something the implementing developer should handle?

If it's the latter, how did you lot do this?

**Comment by compsult** [comment]
What do you think about this approach?

1 - Add date column to user_sessions_session called "last_validated"
2 - datestamp  "last_validated" upon a successful token login
3 - Modify OTPRequiredMixin to 
	query user_sessions_session, if user/agent/ip was "last_validated" in {{trusted_days}}
	allow access if authenticated ( without token )

**Comment by compsult** [comment]
Makes sense. 

Made some progress on the signed cookie front but was hoping you might have some ideas about how to handle OTPRequiredMixin. 
The test request.user.is_verified(), which (from my read) requires that request.user.otp_device be populated. Since I am skipping the token logic when there was a recent validated login ,  request.user.otp_device is not getting populated.
Any ideas on how I might solve this?

**Comment by diegobill** [comment]
:+1:

**Comment by beckedorf** [comment]
I just started a new attempt. But still WIP #352
